@startuml
'https://plantuml.com/class-diagram

abstract class Product
class Order
class Picklist
class Main
class OrderLine


class Order{
- long: orderNo
- long: customerNo
- LocalDate: dato
- ArrayList<listOfOrderLine>
}

class OrderLine{
- String product
- int quanity
}

abstract class Product{
 # String: name
 # int: dbNo
 # String: location
 }
class Picklist{
+ String dato
- ArrayList<String> picklist
}


class Main{
+ String userInput

}

package UTIL{
class TextUI{
- Scanner scan
+ void displayMsg()
}

class FileIO{
+ readData()
}
}
Order -|> OrderLine
OrderLine -|> Product
Picklist -|> Order

Main -> Picklist

UTIL -> Product
UTIL -> Order
UTIL-> Main
UTIL -> Picklist



@enduml